### ISSUE TITLE
libboost_program_options.so.1.72.0 not found

### ISSUE THREAD

**Issue by UE2020** [daniel-araujo/click4ever#2]
I installed this program about 1 month ago. Today when I attempted to use it, I got this error:

`click4ever: error while loading shared libraries: libboost_program_options.so.1.72.0: cannot open shared object file: No such file or directory`

**Comment by G4Zz0L1** [comment]
Yep, same here. Any news on this?

**Comment by UE2020** [comment]
I have a theory that it will work if you try to compile it on your own machine, but I haven't tested it yet.

**Comment by daniel-araujo** [comment]
Did you happen to update libboost after compiling this program? The program is linked to the version of libboost that was installed on your system at the time that the program was compiled. If that is the case, you only have to recompile the program to fix this problem. Recompiling will link the program to the new version of the library.

When you update a library through a package manager, the package manager will automatically update the programs that were linked to the old version of the library. It will only do this for programs that were installed as a package, though. If you're running Arch Linux or any distro that uses `pacman`, you can get click4ever as a convenient package: https://aur.archlinux.org/packages/click4ever
