### ISSUE TITLE
CMake Error: Unknown argument --config

### ISSUE THREAD

**Issue by Kruemmelspalter** [daniel-araujo/click4ever#3]
The only option in `cmake --help` I see is `--preset` Maybe this one works. I'll test it out

**Comment by Kruemmelspalter** [comment]
It works just without the whole `--config Release` (`--preset` didn't work)

**Comment by Kruemmelspalter** [comment]
I submitted a PR for removing it in README.md #4

**Comment by daniel-araujo** [comment]
Thank you for taking the time to report this issue and even provide a solution. This will help a lot of programmers with the same problem.
